// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTVTslEnzBwsOGNvAd1dw7JZGE7mEG2I',
    appId: '1:834074426474:android:c59731f5abecfa364f5e13',
    messagingSenderId: '834074426474',
    projectId: 'egatepass-b9da7',
    storageBucket: 'egatepass-b9da7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSL29AVLVgu5AuUr6RsMYcOofNmIT3FM8',
    appId: '1:834074426474:ios:b0eaab635fa06b344f5e13',
    messagingSenderId: '834074426474',
    projectId: 'egatepass-b9da7',
    storageBucket: 'egatepass-b9da7.firebasestorage.app',
    iosBundleId: 'com.example.eGatepass',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-Js5ou025O8np98cdbcs1-NadgrPSjS8',
    appId: '1:834074426474:web:ae4a56fa5f008e8c4f5e13',
    messagingSenderId: '834074426474',
    projectId: 'egatepass-b9da7',
    authDomain: 'egatepass-b9da7.firebaseapp.com',
    storageBucket: 'egatepass-b9da7.firebasestorage.app',
    measurementId: 'G-6BYECTMR3C',
  );
}
